defmodule Polly.Repo.Migrations.AddPollPrivacyMode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:polls) do
      add :privacy_mode, :text, null: false, default: "identified"
    end
  end

  def down do
    alter table(:polls) do
      remove :privacy_mode
    end
  end
end
