defmodule Polly.Repo.Migrations.AddPollParticipations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:poll_participations, primary_key: false) do
      add :member_id,
          references(:members,
            column: :id,
            name: "poll_participations_member_id_fkey",
            type: :uuid
          ),
          null: false

      add :poll_id,
          references(:polls, column: :id, name: "poll_participations_poll_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :participated_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:poll_participations, [:poll_id, :member_id],
             name: "poll_participations_unique_poll_member_index"
           )

    # Intentionally do not filter null member IDs: the NOT NULL constraint must
    # abort the migration if historical ballot identity is inconsistent.
    execute("""
    INSERT INTO poll_participations (
      id,
      poll_id,
      member_id,
      participated_at,
      inserted_at,
      updated_at
    )
    SELECT
      lower(hex(randomblob(4))) || '-' ||
        lower(hex(randomblob(2))) || '-4' ||
        substr(lower(hex(randomblob(2))), 2) || '-' ||
        substr('89ab', abs(random()) % 4 + 1, 1) ||
        substr(lower(hex(randomblob(2))), 2) || '-' ||
        lower(hex(randomblob(6))),
      poll_id,
      member_id,
      submitted_at,
      inserted_at,
      updated_at
    FROM poll_ballots
    """)
  end

  def down do
    drop_if_exists unique_index(:poll_participations, [:poll_id, :member_id],
                     name: "poll_participations_unique_poll_member_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_participations` table without the `poll_participations_poll_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_participations` table without the `poll_participations_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:poll_participations)
  end
end
