defmodule Polly.Repo.Migrations.AddAdminAuditTrail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :request_id, :text
      add :source, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :poll_id, :uuid
      add :target_label, :text, null: false
      add :target_id, :uuid
      add :target_type, :text, null: false
      add :actor_label, :text, null: false
      add :actor_id, :uuid, null: false
      add :action, :text, null: false
      add :operation_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:audit_events, [:operation_id],
             name: "audit_events_unique_operation_index"
           )

    create index(:audit_events, [:occurred_at, :id], name: "audit_events_timeline_index")
    create index(:audit_events, [:actor_id], name: "audit_events_actor_index")
    create index(:audit_events, [:action], name: "audit_events_action_index")
    create index(:audit_events, [:target_type, :target_id], name: "audit_events_target_index")
    create index(:audit_events, [:poll_id], name: "audit_events_poll_index")
  end

  def down do
    drop_if_exists index(:audit_events, [:poll_id], name: "audit_events_poll_index")

    drop_if_exists index(:audit_events, [:target_type, :target_id],
                     name: "audit_events_target_index"
                   )

    drop_if_exists index(:audit_events, [:action], name: "audit_events_action_index")
    drop_if_exists index(:audit_events, [:actor_id], name: "audit_events_actor_index")
    drop_if_exists index(:audit_events, [:occurred_at, :id], name: "audit_events_timeline_index")

    drop_if_exists unique_index(:audit_events, [:operation_id],
                     name: "audit_events_unique_operation_index"
                   )

    drop table(:audit_events)
  end
end
