defmodule Polly.Repo.Migrations.PhaseOnePollFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:polls, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :results_published_at, :utc_datetime_usec
      add :closed_at, :utc_datetime_usec
      add :opened_at, :utc_datetime_usec
      add :selection_mode, :text, null: false
      add :status, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:polls, [:slug], name: "polls_unique_slug_index")

    create table(:poll_options, primary_key: false) do
      add :poll_id,
          references(:polls, column: :id, name: "poll_options_poll_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :position, :bigint, null: false
      add :label, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:poll_options, [:poll_id, :position],
             name: "poll_options_unique_position_index"
           )
  end

  def down do
    drop_if_exists unique_index(:poll_options, [:poll_id, :position],
                     name: "poll_options_unique_position_index"
                   )

    drop table(:poll_options)

    drop_if_exists unique_index(:polls, [:slug], name: "polls_unique_slug_index")

    drop table(:polls)
  end
end
