defmodule Polly.Repo.Migrations.NormalizeMemberEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("UPDATE members SET email = NULL WHERE trim(email) = ''")
    execute("UPDATE members SET email = lower(trim(email)) WHERE email IS NOT NULL")

    create unique_index(:members, [:email], name: "members_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:members, [:email], name: "members_unique_email_index")
  end
end
