defmodule Polly.Repo.Migrations.AddDerivedVoterCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true

  def up do
    execute("PRAGMA foreign_keys = OFF")

    original_columns = table_columns("poll_access_grants")
    staging_columns = table_columns("poll_access_grants_derived_credentials")

    cond do
      "token_digest" in original_columns ->
        execute("DROP TABLE IF EXISTS poll_access_grants_derived_credentials")

      original_columns != [] ->
        rebuild_with_derived_credentials()

      "token_digest" in staging_columns ->
        execute("ALTER TABLE poll_access_grants_derived_credentials RENAME TO poll_access_grants")

      true ->
        raise "cannot locate the poll_access_grants table or its migration staging table"
    end

    execute("""
    CREATE UNIQUE INDEX IF NOT EXISTS poll_access_grants_unique_token_index
    ON poll_access_grants(token)
    """)

    execute("""
    CREATE UNIQUE INDEX IF NOT EXISTS poll_access_grants_unique_token_digest_index
    ON poll_access_grants(token_digest)
    """)

    execute("PRAGMA foreign_keys = ON")
  end

  def down do
    case repo().query!("SELECT id FROM poll_access_grants WHERE token IS NULL LIMIT 1").rows do
      [] ->
        :ok

      _derived_grants ->
        raise "cannot restore plaintext-only grants after derived credentials exist"
    end

    drop_if_exists unique_index(:poll_access_grants, [:token_digest],
                     name: "poll_access_grants_unique_token_digest_index"
                   )

    execute("PRAGMA foreign_keys = OFF")

    execute("""
    CREATE TABLE poll_access_grants_plaintext_credentials (
      member_id TEXT NOT NULL CONSTRAINT poll_access_grants_member_id_fkey REFERENCES members(id),
      poll_id TEXT NOT NULL CONSTRAINT poll_access_grants_poll_id_fkey REFERENCES polls(id),
      updated_at TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      expires_at TEXT,
      revoked_at TEXT,
      token TEXT NOT NULL,
      id TEXT NOT NULL PRIMARY KEY
    )
    """)

    execute("""
    INSERT INTO poll_access_grants_plaintext_credentials (
      member_id, poll_id, updated_at, inserted_at, expires_at, revoked_at, token, id
    )
    SELECT member_id, poll_id, updated_at, inserted_at, expires_at, revoked_at, token, id
    FROM poll_access_grants
    """)

    execute("DROP TABLE poll_access_grants")

    execute("ALTER TABLE poll_access_grants_plaintext_credentials RENAME TO poll_access_grants")

    execute("""
    CREATE UNIQUE INDEX poll_access_grants_unique_token_index
    ON poll_access_grants(token)
    """)

    execute("PRAGMA foreign_keys = ON")
  end

  defp rebuild_with_derived_credentials do
    execute("DROP TABLE IF EXISTS poll_access_grants_derived_credentials")

    execute("""
    CREATE TABLE poll_access_grants_derived_credentials (
      member_id TEXT NOT NULL CONSTRAINT poll_access_grants_member_id_fkey REFERENCES members(id),
      poll_id TEXT NOT NULL CONSTRAINT poll_access_grants_poll_id_fkey REFERENCES polls(id),
      updated_at TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      expires_at TEXT,
      revoked_at TEXT,
      token TEXT,
      id TEXT NOT NULL PRIMARY KEY,
      token_digest TEXT,
      credential_nonce TEXT,
      credential_version INTEGER NOT NULL DEFAULT 0,
      credential_issued_at TEXT
    )
    """)

    execute("""
    INSERT INTO poll_access_grants_derived_credentials (
      member_id, poll_id, updated_at, inserted_at, expires_at, revoked_at, token, id
    )
    SELECT member_id, poll_id, updated_at, inserted_at, expires_at, revoked_at, token, id
    FROM poll_access_grants
    """)

    execute("DROP TABLE poll_access_grants")

    execute("ALTER TABLE poll_access_grants_derived_credentials RENAME TO poll_access_grants")
  end

  defp table_columns(table) do
    repo()
    |> Ecto.Adapters.SQL.query!("PRAGMA table_info(#{table})", [])
    |> Map.fetch!(:rows)
    |> Enum.map(&Enum.at(&1, 1))
  end
end
