defmodule Polly.Repo.Migrations.AddPollSelectionLimits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:polls) do
      add :minimum_selections, :bigint, null: false, default: 1
      add :maximum_selections, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:polls) do
      remove :maximum_selections
      remove :minimum_selections
    end
  end
end
