defmodule Polly.Repo.Migrations.ScheduledPollLifecyclePhase1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Phase 0 records were deliberately poll-free compatibility probes and
    # cannot be promoted into production lifecycle commands.
    execute "DELETE FROM poll_lifecycle_transitions"

    alter table(:poll_lifecycle_transitions) do
      add :kind, :text, null: false
      add :cancelled_at, :utc_datetime_usec
      add :failure_code, :text

      add :poll_id,
          references(:polls,
            column: :id,
            name: "poll_lifecycle_transitions_poll_id_fkey",
            type: :uuid
          ),
          null: false

      add :scheduled_by_id,
          references(:users,
            column: :id,
            name: "poll_lifecycle_transitions_scheduled_by_id_fkey",
            type: :uuid
          ),
          null: false

      add :replaces_transition_id,
          references(:poll_lifecycle_transitions,
            column: :id,
            name: "poll_lifecycle_transitions_replaces_transition_id_fkey",
            type: :uuid
          )
    end

    create index(:poll_lifecycle_transitions, ["poll_id", "kind"],
             name: "poll_lifecycle_transitions_one_pending_kind_index",
             unique: true,
             where: "state = 'pending'"
           )

    create index(:poll_lifecycle_transitions, ["poll_id", "kind", "state"],
             name: "poll_lifecycle_transitions_poll_kind_state_index"
           )

    create index(:poll_lifecycle_transitions, ["state", "scheduled_at"],
             name: "poll_lifecycle_transitions_due_index"
           )
  end

  def down do
    drop_if_exists index(:poll_lifecycle_transitions, ["state", "scheduled_at"],
                     name: "poll_lifecycle_transitions_due_index"
                   )

    drop_if_exists index(:poll_lifecycle_transitions, ["poll_id", "kind", "state"],
                     name: "poll_lifecycle_transitions_poll_kind_state_index"
                   )

    drop_if_exists index(:poll_lifecycle_transitions, ["poll_id", "kind"],
                     name: "poll_lifecycle_transitions_one_pending_kind_index"
                   )

    alter table(:poll_lifecycle_transitions) do
      remove :replaces_transition_id
      remove :scheduled_by_id
      remove :poll_id
      remove :failure_code
      remove :cancelled_at
      remove :kind
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_lifecycle_transitions` table without the `poll_lifecycle_transitions_poll_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_lifecycle_transitions` table without the `poll_lifecycle_transitions_scheduled_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_lifecycle_transitions` table without the `poll_lifecycle_transitions_replaces_transition_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
