defmodule Polly.Repo.Migrations.UseUniqueOptionPerBallot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:poll_selections, [:ballot_id],
                     name: "poll_selections_one_selection_per_ballot_index"
                   )

    create unique_index(:poll_selections, [:ballot_id, :option_id],
             name: "poll_selections_unique_option_per_ballot_index"
           )
  end

  def down do
    case repo().query!("""
         SELECT ballot_id
         FROM poll_selections
         GROUP BY ballot_id
         HAVING COUNT(*) > 1
         LIMIT 1
         """).rows do
      [] ->
        :ok

      _multiple_selection_ballot ->
        raise "cannot restore the single-selection identity while a ballot has multiple selections"
    end

    drop_if_exists unique_index(:poll_selections, [:ballot_id, :option_id],
                     name: "poll_selections_unique_option_per_ballot_index"
                   )

    create unique_index(:poll_selections, [:ballot_id],
             name: "poll_selections_one_selection_per_ballot_index"
           )
  end
end
