defmodule Polly.Repo.Migrations.PinInvitationCredentialVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:poll_invitation_deliveries) do
      add :credential_version, :bigint, null: false, default: 0
    end

    execute("""
    UPDATE poll_invitation_deliveries
    SET credential_version = COALESCE(
      (
        SELECT credential_version
        FROM poll_access_grants
        WHERE poll_access_grants.id = poll_invitation_deliveries.access_grant_id
      ),
      0
    )
    """)
  end

  def down do
    alter table(:poll_invitation_deliveries) do
      remove :credential_version
    end
  end
end
