defmodule Polly.Repo.Migrations.AddPollInvitationDeliveries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:poll_invitation_deliveries, primary_key: false) do
      add :access_grant_id,
          references(:poll_access_grants,
            column: :id,
            name: "poll_invitation_deliveries_access_grant_id_fkey",
            type: :uuid
          ),
          null: false

      add :member_id,
          references(:members,
            column: :id,
            name: "poll_invitation_deliveries_member_id_fkey",
            type: :uuid
          ),
          null: false

      add :poll_id,
          references(:polls,
            column: :id,
            name: "poll_invitation_deliveries_poll_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :cancelled_at, :utc_datetime_usec
      add :failed_at, :utc_datetime_usec
      add :accepted_at, :utc_datetime_usec
      add :requested_at, :utc_datetime_usec, null: false
      add :last_error_code, :text
      add :provider_message_id, :text
      add :attempt_count, :bigint, null: false
      add :requested_by_id, :uuid, null: false
      add :recipient_email, :text, null: false
      add :status, :text, null: false
      add :dedupe_key, :text, null: false
      add :kind, :text, null: false
      add :operation_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:poll_invitation_deliveries, [:dedupe_key],
             name: "poll_invitation_deliveries_unique_dedupe_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:poll_invitation_deliveries, [:dedupe_key],
                     name: "poll_invitation_deliveries_unique_dedupe_key_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_invitation_deliveries` table without the `poll_invitation_deliveries_poll_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_invitation_deliveries` table without the `poll_invitation_deliveries_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_invitation_deliveries` table without the `poll_invitation_deliveries_access_grant_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:poll_invitation_deliveries)
  end
end
