defmodule Polly.Repo.Migrations.ScheduledPollLifecyclePhase0 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:poll_lifecycle_transitions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :state, :text, null: false
      add :scheduled_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:poll_lifecycle_transitions)
  end
end
