defmodule Polly.Repo.Migrations.AddBallotPrivacySnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # SQLite cannot change a column's nullability in place, so preserve the
    # rows while rebuilding ballots and the selections table that references it.
    # The IF EXISTS cleanup also makes a retry safe after the original migration
    # stopped while dropping the referenced ballot table.
    execute("DROP TABLE IF EXISTS poll_selections_new")
    execute("DROP TABLE IF EXISTS poll_ballots_new")

    execute("""
    CREATE TABLE poll_ballots_new (
      id TEXT NOT NULL PRIMARY KEY,
      submitted_at TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      poll_id TEXT NOT NULL,
      member_id TEXT,
      privacy_mode TEXT NOT NULL DEFAULT 'identified',
      CONSTRAINT poll_ballots_poll_id_fkey
        FOREIGN KEY (poll_id) REFERENCES polls(id),
      CONSTRAINT poll_ballots_member_id_fkey
        FOREIGN KEY (member_id) REFERENCES members(id),
      CONSTRAINT poll_ballots_privacy_member_check CHECK (
        (privacy_mode = 'identified' AND member_id IS NOT NULL) OR
        (privacy_mode = 'anonymous' AND member_id IS NULL)
      )
    )
    """)

    execute("""
    INSERT INTO poll_ballots_new (
      id, submitted_at, inserted_at, updated_at, poll_id, member_id, privacy_mode
    )
    SELECT id, submitted_at, inserted_at, updated_at, poll_id, member_id, 'identified'
    FROM poll_ballots
    """)

    execute("""
    CREATE TABLE poll_selections_new (
      id TEXT NOT NULL PRIMARY KEY,
      inserted_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      ballot_id TEXT NOT NULL,
      option_id TEXT NOT NULL,
      CONSTRAINT poll_selections_ballot_id_fkey
        FOREIGN KEY (ballot_id) REFERENCES poll_ballots_new(id),
      CONSTRAINT poll_selections_option_id_fkey
        FOREIGN KEY (option_id) REFERENCES poll_options(id)
    )
    """)

    execute("""
    INSERT INTO poll_selections_new (id, inserted_at, updated_at, ballot_id, option_id)
    SELECT id, inserted_at, updated_at, ballot_id, option_id
    FROM poll_selections
    """)

    execute("DROP TABLE poll_selections")
    execute("DROP TABLE poll_ballots")
    execute("ALTER TABLE poll_ballots_new RENAME TO poll_ballots")
    execute("ALTER TABLE poll_selections_new RENAME TO poll_selections")

    create unique_index(:poll_ballots, [:poll_id, :member_id],
             name: "poll_ballots_unique_poll_member_index"
           )

    create unique_index(:poll_selections, [:ballot_id, :option_id],
             name: "poll_selections_unique_option_per_ballot_index"
           )
  end

  def down do
    execute("DROP TABLE IF EXISTS poll_selections_old")
    execute("DROP TABLE IF EXISTS poll_ballots_old")

    execute("""
    CREATE TABLE poll_ballots_old (
      id TEXT NOT NULL PRIMARY KEY,
      submitted_at TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      poll_id TEXT NOT NULL,
      member_id TEXT NOT NULL,
      CONSTRAINT poll_ballots_poll_id_fkey
        FOREIGN KEY (poll_id) REFERENCES polls(id),
      CONSTRAINT poll_ballots_member_id_fkey
        FOREIGN KEY (member_id) REFERENCES members(id)
    )
    """)

    execute("""
    INSERT INTO poll_ballots_old (id, submitted_at, inserted_at, updated_at, poll_id, member_id)
    SELECT id, submitted_at, inserted_at, updated_at, poll_id, member_id
    FROM poll_ballots
    """)

    execute("""
    CREATE TABLE poll_selections_old (
      id TEXT NOT NULL PRIMARY KEY,
      inserted_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      ballot_id TEXT NOT NULL,
      option_id TEXT NOT NULL,
      CONSTRAINT poll_selections_ballot_id_fkey
        FOREIGN KEY (ballot_id) REFERENCES poll_ballots_old(id),
      CONSTRAINT poll_selections_option_id_fkey
        FOREIGN KEY (option_id) REFERENCES poll_options(id)
    )
    """)

    execute("""
    INSERT INTO poll_selections_old (id, inserted_at, updated_at, ballot_id, option_id)
    SELECT id, inserted_at, updated_at, ballot_id, option_id
    FROM poll_selections
    """)

    execute("DROP TABLE poll_selections")
    execute("DROP TABLE poll_ballots")
    execute("ALTER TABLE poll_ballots_old RENAME TO poll_ballots")
    execute("ALTER TABLE poll_selections_old RENAME TO poll_selections")

    create unique_index(:poll_ballots, [:poll_id, :member_id],
             name: "poll_ballots_unique_poll_member_index"
           )

    create unique_index(:poll_selections, [:ballot_id, :option_id],
             name: "poll_selections_unique_option_per_ballot_index"
           )
  end
end
