defmodule Polly.Repo.Migrations.PhaseThreeABallots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:poll_ballots, primary_key: false) do
      add :member_id,
          references(:members, column: :id, name: "poll_ballots_member_id_fkey", type: :uuid),
          null: false

      add :poll_id,
          references(:polls, column: :id, name: "poll_ballots_poll_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :submitted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:poll_selections, primary_key: false) do
      add :option_id,
          references(:poll_options,
            column: :id,
            name: "poll_selections_option_id_fkey",
            type: :uuid
          ),
          null: false

      add :ballot_id,
          references(:poll_ballots,
            column: :id,
            name: "poll_selections_ballot_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:poll_selections, [:ballot_id],
             name: "poll_selections_one_selection_per_ballot_index"
           )

    create unique_index(:poll_ballots, [:poll_id, :member_id],
             name: "poll_ballots_unique_poll_member_index"
           )
  end

  def down do
    drop_if_exists unique_index(:poll_ballots, [:poll_id, :member_id],
                     name: "poll_ballots_unique_poll_member_index"
                   )

    drop_if_exists unique_index(:poll_selections, [:ballot_id],
                     name: "poll_selections_one_selection_per_ballot_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_ballots` table without the `poll_ballots_poll_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_ballots` table without the `poll_ballots_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:poll_ballots)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_selections` table without the `poll_selections_ballot_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_selections` table without the `poll_selections_option_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:poll_selections)
  end
end
