defmodule Polly.Repo.Migrations.AdminUserManagementPhase1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    CREATE TABLE users_phase_one (
      id TEXT PRIMARY KEY NOT NULL,
      email CITEXT NOT NULL,
      hashed_password TEXT NOT NULL,
      confirmed_at TEXT,
      role TEXT NOT NULL DEFAULT 'administrator',
      status TEXT NOT NULL DEFAULT 'active',
      disabled_at TEXT,
      last_signed_in_at TEXT,
      inserted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """

    execute """
    INSERT INTO users_phase_one (
      id, email, hashed_password, confirmed_at, role, status, inserted_at, updated_at
    )
    SELECT
      id,
      email,
      hashed_password,
      confirmed_at,
      'owner',
      'active',
      strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
      strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    FROM users
    """

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")
    execute "DROP TABLE users"
    execute "ALTER TABLE users_phase_one RENAME TO users"
    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    raise """
    Refusing to roll back administrator roles and statuses because doing so
    would discard account ownership and lifecycle data.
    """
  end
end
