defmodule Polly.Repo.Migrations.AddReminderDeliveryKindAndHistoryIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(
             :poll_invitation_deliveries,
             ["poll_id", "member_id", "kind", "status", "accepted_at"],
             name: "poll_invitation_deliveries_reminder_history_index"
           )
  end

  def down do
    drop_if_exists index(
                     :poll_invitation_deliveries,
                     ["poll_id", "member_id", "kind", "status", "accepted_at"],
                     name: "poll_invitation_deliveries_reminder_history_index"
                   )
  end
end
