defmodule Polly.Repo.Migrations.AddMembersAndPollAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:poll_eligibilities, primary_key: false) do
      add :member_id,
          references(:members,
            column: :id,
            name: "poll_eligibilities_member_id_fkey",
            type: :uuid
          ),
          null: false

      add :poll_id,
          references(:polls, column: :id, name: "poll_eligibilities_poll_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:poll_access_grants, primary_key: false) do
      add :member_id,
          references(:members,
            column: :id,
            name: "poll_access_grants_member_id_fkey",
            type: :uuid
          ),
          null: false

      add :poll_id,
          references(:polls, column: :id, name: "poll_access_grants_poll_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec
      add :token, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:members, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :email, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:poll_eligibilities, [:poll_id, :member_id],
             name: "poll_eligibilities_unique_poll_member_index"
           )

    create unique_index(:poll_access_grants, [:token],
             name: "poll_access_grants_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:poll_access_grants, [:token],
                     name: "poll_access_grants_unique_token_index"
                   )

    drop_if_exists unique_index(:poll_eligibilities, [:poll_id, :member_id],
                     name: "poll_eligibilities_unique_poll_member_index"
                   )

    drop table(:members)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_access_grants` table without the `poll_access_grants_poll_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_access_grants` table without the `poll_access_grants_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:poll_access_grants)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_eligibilities` table without the `poll_eligibilities_poll_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `poll_eligibilities` table without the `poll_eligibilities_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:poll_eligibilities)
  end
end
